### ISSUE TITLE
你好 step5_LDA时候报错

### ISSUE THREAD

**Issue by nasa1024** [KimMeen/Weibo-Analyst#2]
![image](https://user-images.githubusercontent.com/28981872/43774961-88f451d4-9a7d-11e8-933b-7ba1195620c8.png)
第一次出错加上了 文件夹log，第二次就没法解决了。还想请问您一下，是否是python版本问题

**Comment by KimMeen** [comment]
你好，这个错误感觉像是路径错误，请你确认自己的文件夹路径是否完整或合法。python适应版本为3.6。
