### ISSUE TITLE
算法问题

### ISSUE THREAD

**Issue by DongminZhao** [KimMeen/Weibo-Analyst#3]
请问LDAModel 类的逻辑用的是什么算法思想，topic用随机数不太理解

**Comment by KimMeen** [comment]
@DongminZhao 
1. `topic = random.randint(0,self.K-1)`用于初始化主题分布
2. LDA算法原理及实现可以[参考这里](http://skyhigh233.com/blog/2016/10/20/lda-realize/)

**Comment by DongminZhao** [comment]
感谢！
