### ISSUE TITLE
step5_LDA模块

### ISSUE THREAD

**Issue by wj-ccccc** [KimMeen/Weibo-Analyst#4]
请问在第五个模块中提取完后的数据应该如何处理就可以达到测试时演示的效果呢

**Comment by ZClcw** [comment]
同问

**Comment by ZClcw** [comment]
> 请问在第五个模块中提取完后的数据应该如何处理就可以达到测试时演示的效果呢

你好 请问你解决了吗

**Comment by KimMeen** [comment]
1. 聚类结果：model_twords.dat
2. Document-topic 分布: model_theta.dat
3. Word-topic 分布: model_phi.dat

结合聚类结果和Document-topic分布可以分析出演示的文档

**Comment by ZClcw** [comment]
> 1. 聚类结果：model_twords.dat
> 2. Document-topic 分布: model_theta.dat
> 3. Word-topic 分布: model_phi.dat
> 
> 结合聚类结果和Document-topic分布可以分析出演示的文档
好的！十分感谢您！
